os:
  - linux
dist: trusty
language: node_js
node_js:
  - "6.10.0"
jdk:
  - oraclejdk8
sudo: false
branches:
  only:
  - master
  - dev
cache:
  directories:
    - node
    - node_modules
    - $HOME/.m2
env:
  global:
    - NODE_VERSION=6.10.0
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
addons:
  chrome: stable
  apt:
    packages:
      - oracle-java8-set-default
before_install:
  - nvm install $NODE_VERSION
  - node -v
  - npm -v
  - java -version
install:
  - cd ./festival/frontend
  - npm install
  - cd ..
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - chmod +x ./mvnw
  - ./mvnw clean test
  - cd ./frontend
  - npm test
#after_success:
  - cd ../..
  - chmod +x ./deploy.sh
  - ./deploy.sh
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false